name: Release Build

on:
  release:
    types: [published]

jobs:
  build-and-upload-binary:
    name: Build and Upload Binary to release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout project

      - uses: dtolnay/rust-toolchain@stable
        name: Install the Rust toolchain

      - uses: Swatinem/rust-cache@v2
        name: Use cached dependencies and artifacts

      - run: cargo build --release
        name: Build release binary

      - uses: softprops/action-gh-release@v2
        name: Upload binary to release
        if: github.ref_type == 'tag'
        with:
          files: target/release/chess-tui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
